### ISSUE TITLE
Relative scores not accessible

### ISSUE THREAD

**Issue by MPDeanUCL** [amith-ananthram/feelingblue#1]
With the link to the Derived Relative Emotion Scores, I get an error: “The main branch of feelingblue does not contain the path corpora/feelingblue_relative_scores.csv.”

It would be great to be able to access these scores. The dataset as a whole is useful and the emotion scores even moe so.

Best wishes.

**Comment by amith-ananthram** [comment]
Hi @MPDeanUCL, thank you for filing this!  Totally missed that it wasn't uploaded.  Will look into it today and get back to you by EOD.

**Comment by amith-ananthram** [comment]
hi @MPDeanUCL, i've added the missing relative score CSV in this PR: https://github.com/amith-ananthram/feelingblue/pull/2.  thanks again for your interest and reporting the issue and apologies for the slow turnaround!  please let me know if you run into any further problems and happy new year!

**Comment by MPDeanUCL** [comment]
Thanks!

Dr Michael Dean
UCL Language and Cognition
Chandler House, 2 Wakefield Street
London, WC1N 1PF
Tel: 020 7679 4249
Email: ***@***.******@***.***>
https://profiles.ucl.ac.uk/32275-michael-dean
He/him
